### ISSUE TITLE
Hello from LuaConsole

### ISSUE THREAD

**Issue by tilkinsc** [giann/croissant#1]
Hello! I own https://github.com/tilkinsc/LuaConsole
`A next-gen, Cross-Platform [Lua-5.1.x, LuaJIT-2.0, Lua-5.2.x, Lua5.3.x]-supporting CLI made to supersede PUC-Lua and LuaJIT CLI http://tilkinsc.github.io/LuaConsole/`

I like croissant's style. I would appreciate contributions to my REPL portion of my project in any way you can think of to improve the project. Such as pretty printing return values. That would be amazing.

Thanks

**Comment by giann** [comment]
Hi there. You're welcome to use croissant in any shape of form within the boundaries of its license.
