### ISSUE TITLE
croissant breaks with sirocco error

### ISSUE THREAD

**Issue by ahillio** [giann/croissant#8]
I just got croissant installed, run `croissant` from zsh shell, and croissant breaks on the first command I type printing the same stack trace as https://github.com/giann/sirocco/issues/2

```
❯ croissant
🥐  Croissant 0.0.1 (C) 2019 Benoit Giannangeli
Lua 5.1 Copyright (C) 1994-2018 Lua.org, PUC-Rio
myvar = "banana"
/usr/bin/lua5.1: ...3.8.0/./lua_modules/share/lua/5.1/sirocco/prompt.lua:355: attempt to perform arithmetic on field 'y' (a nil value)
stack traceback:
        [C]: ?
        ...3.8.0/./lua_modules/share/lua/5.1/sirocco/prompt.lua:355: in function 'update'
        ...3.8.0/./lua_modules/share/lua/5.1/sirocco/prompt.lua:429: in function 'ask'
        ...3.8.0/./lua_modules/share/lua/5.1/croissant/repl.lua:29: in function <...3.8.0/./lua_modules/share/lua/5.1/croissant/repl.lua:10>
        ...b/luarocks/rocks-5.1/croissant/0.0.1-6/bin/croissant:52: in function 'route'
        ...b/luarocks/rocks-5.1/croissant/0.0.1-6/bin/croissant:56: in main chunk
        [C]: ?
↵ Error. Exit status 1.                                          
```
When `croissant` first loads, it presents the characters `^[[28;1R` at the top just after the copyright info.

If I delete those characters then type `myvar = "random string"` then I get that stacktrace when I hit Enter key.

If I hit Enter key without deleting those characters, then I get:

```
❯ croissant
🥐  Croissant 0.0.1 (C) 2019 Benoit Giannangeli
Lua 5.1 Copyright (C) 1994-2018 Lua.org, PUC-Rio
→
/usr/bin/env: ‘stty’: No such file or directory

→
/usr/bin/env: ‘stty’: No such file or directory

^[[34;1Rcl^C
```

...notice how `^C` (Ctrl C) did not cancel/exit the process/thing.

**Comment by giann** [comment]
Sirocco (upon which croissant is built) needs the unix command `stty` in order to put the terminal in raw mode. Seems like `env` can't find it on your system.
